point_cal_simulation:
  ros__parameters:
    topic_object: 'HsinChiaChen'
    radius: 1.0
    circle_num: 101
    laser_max_dis: 5.0
    coff_static_obstacle: 0.5
    obstacle_safe_dis: 0.5
    coff_robot_ang: 1.0
    topic_person: 'person_array'
    base_link_frame: 'base_link'
    camera_frame: 'camera_link'
    base_scan_frame: 'base_scan'

